### ISSUE TITLE
请教：操作系统安卓，运行平台支付宝，视频层级会变成最高

### ISSUE THREAD

**Issue by AsherSun** [elf-templates/video#3]
前辈，我想请教个问题：

**问题描述：**
+ 操作系统：安卓
+ 运行平台：支付宝
+ 问题：视频播放的时候层级会变成最高

**针对上述问题，有没有针对阿里系的<code>webview</code>优化方向或方式方法**

@booxood @koppthe

**Comment by booxood** [comment]
没接触过 不了解
